### ISSUE TITLE
/GTS Não esta funcionando

### ISSUE THREAD

**Issue by TheNage** [NickImpact/GTS#32]
Problema ao digitar /GTS.

Nucleus: 1.5.4
GTS: 3.11.0
Impactor: 1.4.0

erro console:
[13:40:47] [Server thread/INFO] [nucleus]: The_Nage ran the command: /gts
[13:40:47] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'gts' for source EntityPlayerMP['The_Nage'/2, l='world', x=1763,92, y=4,00, z=1697,42]: com/pixelmonmod/pixelmon/enums/forms/EnumBidoof
java.lang.NoClassDefFoundError: com/pixelmonmod/pixelmon/enums/forms/EnumBidoof
        at com.nickimpact.gts.ui.MainUI.design(MainUI.java:133) ~[MainUI.class:?]
        at com.nickimpact.gts.ui.MainUI.<init>(MainUI.java:78) ~[MainUI.class:?]
        at com.nickimpact.gts.ui.MainUI.<init>(MainUI.java:55) ~[MainUI.class:?]
        at com.nickimpact.gts.commands.GTSBaseCmd.execute(GTSBaseCmd.java:61) ~[GTSBaseCmd.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:250) ~[ChildCommandElementExecutor.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3361]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:329) [SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3361]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:92) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3361]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zle000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3361]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3963) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by NickImpact** [comment]
Which version of Pixelmon do you have installed? Reforged, generations, and exact version number

**Comment by TheNage** [comment]
Pixelmon Generation 2.2.1

**Comment by NickImpact** [comment]
That’d be why. GTS doesn’t support generations in its current state, and has no plans to do so. Another dev can fork my work and provide support for it, under the provided license of course. Other than that, it won’t be me handling the task. Highly recommend updating to reforged.
